### ISSUE TITLE
Better Background Image Required

### ISSUE THREAD

**Issue by ThePsyk3y** [ThePsyk3y/JS-Calc#8]
The website's current background image is quite lackluster and bland.
A well designed wallpaper is need for a visual revamp.

**Comment by sakshi-choudhary** [comment]
I would like to work on this. Could you assign me?

**Comment by ThePsyk3y** [comment]
Sure @sakshi-choudhary, Anything angular with a yellow theme would be great. Otherwise anything geometric would be fine.

**Comment by sakshi-choudhary** [comment]
Hey, @ThePsyk3y please review my PR #10
